version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get install -y maven
  build:
    commands:
      - mvn clean install -f pom.xml
artifacts:
  files:
    - 'path/to/java-tomcat.war'
